version: '3.4'

services:
  textclassify:
    image: textclassify
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5050:5050
    volumes:
      - ./models:/app/models      
